import os
import sqlite3
import time
from datetime import datetime, date
from typing import Any, Dict, List, Optional

DB_PATH = os.path.join("data", "project_puma.db")

def _now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")

def _try_get_sf_session():
    try:
        from snowflake.snowpark.context import get_active_session  # type: ignore
        return get_active_session()
    except Exception:
        return None

def backend() -> str:
    return "snowflake" if _try_get_sf_session() is not None else "sqlite"

def _retry_locked(fn, retries: int = 20):
    for i in range(retries):
        try:
            return fn()
        except sqlite3.OperationalError as e:
            if "locked" in str(e).lower():
                time.sleep(0.15 * (i + 1))
                continue
            raise
    raise sqlite3.OperationalError("database is locked (retry exhausted)")

# ---------------- SQLITE ----------------
def _sqlite_conn():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    # isolation_level=None = autocommit (reduces weird lock behavior around PRAGMAs)
    conn = sqlite3.connect(DB_PATH, timeout=30, isolation_level=None, check_same_thread=False)
    conn.row_factory = sqlite3.Row

    # Always set busy timeout first
    conn.execute("PRAGMA busy_timeout=30000;")
    conn.execute("PRAGMA foreign_keys=ON;")

    # WAL is great, but it can be locked briefly if another process has the DB open.
    # So we retry instead of crashing the app.
    for i in range(30):
        try:
            conn.execute("PRAGMA journal_mode=WAL;")
            conn.execute("PRAGMA synchronous=NORMAL;")
            break
        except sqlite3.OperationalError as e:
            if "locked" in str(e).lower():
                time.sleep(0.15 * (i + 1))
                continue
            raise

    return conn

def _sqlite_cols(conn: sqlite3.Connection, table: str) -> List[str]:
    rows = conn.execute(f"PRAGMA table_info({table});").fetchall()
    return [r["name"] for r in rows]

def init_storage() -> None:
    if backend() == "snowflake":
        s = _try_get_sf_session()
        assert s is not None
        # Put tables in the app schema.
        s.sql("""
        CREATE TABLE IF NOT EXISTS PUMA_SHIFTS(
          ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
          SHIFT_DATE DATE NOT NULL,
          SHIFT_TYPE STRING NOT NULL,
          USERNAME STRING NOT NULL,
          VEHICLE STRING NOT NULL,
          JOB_NUMBER STRING,
          SITE_NAME STRING,
          SHIFT_START STRING,
          SHIFT_HOURS FLOAT,
          SHIFT_NOTES STRING,
          CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
          UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
        );
        """).collect()

        s.sql("""
        CREATE TABLE IF NOT EXISTS PUMA_ACTIVITIES(
          ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
          SHIFT_ID NUMBER NOT NULL,
          START_TS TIMESTAMP_NTZ NOT NULL,
          END_TS TIMESTAMP_NTZ,
          CODE STRING NOT NULL,
          TITLE STRING NOT NULL,
          NOTES STRING,
          TOOL_REF STRING,
          CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
          UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
        );
        """).collect()
        return

    conn = _sqlite_conn()
    cur = conn.cursor()

    cur.execute("""
    CREATE TABLE IF NOT EXISTS shifts(
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_date TEXT NOT NULL,
      shift_type TEXT NOT NULL,
      username TEXT NOT NULL,
      vehicle TEXT NOT NULL,
      job_number TEXT,
      site_name TEXT,
      shift_start TEXT,
      shift_hours REAL,
      shift_notes TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(shift_date, shift_type, username)
    );
    """)

    cur.execute("""
    CREATE TABLE IF NOT EXISTS activities(
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      shift_id INTEGER NOT NULL,
      start_ts TEXT NOT NULL,
      end_ts TEXT,
      code TEXT NOT NULL,
      title TEXT NOT NULL,
      notes TEXT,
      tool_ref TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY(shift_id) REFERENCES shifts(id)
    );
    """)

    conn.commit()

    # Migrate older DBs (add any missing columns)
    cols = _sqlite_cols(conn, "shifts")
    def add_col(name: str, ddl: str):
        if name not in cols:
            _retry_locked(lambda: cur.execute(ddl))

    add_col("job_number", "ALTER TABLE shifts ADD COLUMN job_number TEXT;")
    add_col("site_name", "ALTER TABLE shifts ADD COLUMN site_name TEXT;")
    add_col("shift_start", "ALTER TABLE shifts ADD COLUMN shift_start TEXT;")
    add_col("shift_hours", "ALTER TABLE shifts ADD COLUMN shift_hours REAL;")
    add_col("shift_notes", "ALTER TABLE shifts ADD COLUMN shift_notes TEXT;")

    conn.commit()
    conn.close()

def get_shift(shift_date: date, shift_type: str, username: str) -> Optional[Dict[str, Any]]:
    init_storage()
    if backend() == "snowflake":
        s = _try_get_sf_session()
        assert s is not None
        rows = s.sql("""
          SELECT *
          FROM PUMA_SHIFTS
          WHERE SHIFT_DATE = ? AND SHIFT_TYPE = ? AND USERNAME = ?
          ORDER BY UPDATED_AT DESC, ID DESC
          LIMIT 1
        """, params=[shift_date, shift_type, username]).collect()
        if not rows:
            return None
        r = rows[0]
        return {
            "id": int(r["ID"]),
            "shift_date": str(r["SHIFT_DATE"]),
            "shift_type": r["SHIFT_TYPE"],
            "username": r["USERNAME"],
            "vehicle": r["VEHICLE"],
            "job_number": r.get("JOB_NUMBER"),
            "site_name": r.get("SITE_NAME"),
            "shift_start": r.get("SHIFT_START"),
            "shift_hours": r.get("SHIFT_HOURS"),
            "shift_notes": r.get("SHIFT_NOTES"),
        }

    conn = _sqlite_conn()
    row = conn.execute(
        "SELECT * FROM shifts WHERE shift_date=? AND shift_type=? AND username=?",
        (shift_date.isoformat(), shift_type, username),
    ).fetchone()
    conn.close()
    return dict(row) if row else None

def upsert_shift(
    shift_date: date,
    shift_type: str,
    username: str,
    vehicle: str,
    job_number: str = "",
    site_name: str = "",
    shift_start: str = "",
    shift_hours: float = 12.0,
    shift_notes: str = "",
) -> int:
    init_storage()
    if backend() == "snowflake":
        s = _try_get_sf_session()
        assert s is not None

        existing = get_shift(shift_date, shift_type, username)
        if existing:
            sid = int(existing["id"])
            s.sql("""
              UPDATE PUMA_SHIFTS
              SET VEHICLE=?, JOB_NUMBER=?, SITE_NAME=?, SHIFT_START=?, SHIFT_HOURS=?, SHIFT_NOTES=?, UPDATED_AT=CURRENT_TIMESTAMP()
              WHERE ID=?
            """, params=[vehicle, job_number, site_name, shift_start, float(shift_hours), shift_notes, sid]).collect()
            return sid

        s.sql("""
          INSERT INTO PUMA_SHIFTS(SHIFT_DATE, SHIFT_TYPE, USERNAME, VEHICLE, JOB_NUMBER, SITE_NAME, SHIFT_START, SHIFT_HOURS, SHIFT_NOTES)
          VALUES(?,?,?,?,?,?,?,?,?)
        """, params=[shift_date, shift_type, username, vehicle, job_number, site_name, shift_start, float(shift_hours), shift_notes]).collect()

        created = get_shift(shift_date, shift_type, username)
        assert created is not None
        return int(created["id"])

    conn = _sqlite_conn()
    cur = conn.cursor()

    # Insert if missing
    cur.execute("""
      INSERT OR IGNORE INTO shifts
      (shift_date, shift_type, username, vehicle, job_number, site_name, shift_start, shift_hours, shift_notes, created_at, updated_at)
      VALUES(?,?,?,?,?,?,?,?,?,?,?)
    """, (
        shift_date.isoformat(), shift_type, username, vehicle,
        job_number or None, site_name or None, shift_start or None, float(shift_hours),
        shift_notes or None, _now_iso(), _now_iso()
    ))

    # Update always
    cur.execute("""
      UPDATE shifts
      SET vehicle=?, job_number=?, site_name=?, shift_start=?, shift_hours=?, shift_notes=?, updated_at=?
      WHERE shift_date=? AND shift_type=? AND username=?
    """, (
        vehicle, job_number or None, site_name or None, shift_start or None, float(shift_hours),
        shift_notes or None, _now_iso(),
        shift_date.isoformat(), shift_type, username
    ))

    conn.commit()
    sid = conn.execute(
        "SELECT id FROM shifts WHERE shift_date=? AND shift_type=? AND username=?",
        (shift_date.isoformat(), shift_type, username),
    ).fetchone()["id"]
    conn.close()
    return int(sid)

def list_activities(shift_id: int) -> List[Dict[str, Any]]:
    init_storage()
    if backend() == "snowflake":
        s = _try_get_sf_session()
        assert s is not None
        rows = s.sql("""
          SELECT
            ID, SHIFT_ID,
            TO_VARCHAR(START_TS, 'YYYY-MM-DD\"T\"HH24:MI:SS') AS START_TS,
            IFF(END_TS IS NULL, NULL, TO_VARCHAR(END_TS, 'YYYY-MM-DD\"T\"HH24:MI:SS')) AS END_TS,
            CODE, TITLE, NOTES, TOOL_REF
          FROM PUMA_ACTIVITIES
          WHERE SHIFT_ID = ?
          ORDER BY START_TS ASC, ID ASC
        """, params=[int(shift_id)]).collect()
        return [r.as_dict() for r in rows]

    conn = _sqlite_conn()
    rows = conn.execute(
        "SELECT * FROM activities WHERE shift_id=? ORDER BY start_ts ASC, id ASC",
        (int(shift_id),),
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]

def add_activity(shift_id: int, start_ts: str, end_ts: Optional[str], code: str, title: str, notes: str = "", tool_ref: str = "") -> None:
    init_storage()
    if backend() == "snowflake":
        s = _try_get_sf_session()
        assert s is not None
        s.sql("""
          INSERT INTO PUMA_ACTIVITIES(SHIFT_ID, START_TS, END_TS, CODE, TITLE, NOTES, TOOL_REF)
          SELECT
            ?, TO_TIMESTAMP_NTZ(?),
            IFF(? IS NULL OR ? = '', NULL, TO_TIMESTAMP_NTZ(?)),
            ?, ?, NULLIF(?, ''), NULLIF(?, '')
        """, params=[int(shift_id), start_ts, end_ts, end_ts or "", end_ts or "", code, title, notes or "", tool_ref or ""]).collect()
        return

    conn = _sqlite_conn()
    cur = conn.cursor()
    cur.execute("""
      INSERT INTO activities(shift_id, start_ts, end_ts, code, title, notes, tool_ref, created_at, updated_at)
      VALUES(?,?,?,?,?,?,?,?,?)
    """, (int(shift_id), start_ts, end_ts, code, title, notes or None, tool_ref or None, _now_iso(), _now_iso()))
    conn.commit()
    conn.close()

def delete_activity(activity_id: int) -> None:
    init_storage()
    if backend() == "snowflake":
        s = _try_get_sf_session()
        assert s is not None
        s.sql("DELETE FROM PUMA_ACTIVITIES WHERE ID=?", params=[int(activity_id)]).collect()
        return

    conn = _sqlite_conn()
    conn.execute("DELETE FROM activities WHERE id=?", (int(activity_id),))
    conn.commit()
    conn.close()
